.TH lattice 3 "May 2023" "cmark 0.1.0" "Library Functions Manual"

.SH NAME
.PP
\f[B]lattice\f[] \- Lattice C templating engine

.SH "DESCRIPTION"
\f[B]lattice\f[] is a templating engine written in pure C. It operates on JSON
data and supports basic operations on the data, including complex selection and
iteration with extended expressions.

.SH "SEE ALSO"
.PP
See <\f[C]https://github.com/19wintersp/Lattice\f[]> to report bugs and see more
detailed documentation, including for the templating language itself.
